S3_BUCKET_NAME: your-s3-bucket-name
EMAILS_TABLE_NAME: your-emails-table-name
SUBSCRIBERS_TABLE_NAME: your-subscribers-table-name
AGENTS_ALLOCATION_TABLE_NAME: your-agents-allocation-table-name
GOOGLE_CLIENT_ID: your-google-oauth-client-id
GOOGLE_CLIENT_SECRET: your-google-oauth-client-secret
GOOGLE_AUTH_REDIRECT_URI: your-google-auth-redirect-uri
AGENT_RUNTIME_ARN: arn:aws:bedrock-agentcore:us-east-1:....
INVITE_CODE: INVITE_CODE
SES_FROM_EMAIL: wellcome@example.com

